#!/bin/sh
#
# @name Chain-Wing UAV (3-unit)
#
# @type Standard Plane
# @class Plane
#
# @output MAIN1 Motor 1 (left unit)
# @output MAIN2 Motor 2 (center unit)
# @output MAIN3 Motor 3 (right unit)
# @output MAIN4 Right Elevon (left unit - reversed for chain-wing roll stability)
# @output MAIN5 Elevator (center unit)
# @output MAIN6 Left Elevon (right unit - reversed for chain-wing roll stability)
#
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default CA_AIRFRAME 1

# --- Three motors for differential thrust yaw control ---
param set-default CA_ROTOR_COUNT 3

# Motor 0: left unit (Y = -0.6m from center)
param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY -0.6
param set-default CA_ROTOR0_PZ 0.0

# Motor 1: center unit (Y = 0.0m)
param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY 0.0
param set-default CA_ROTOR1_PZ 0.0

# Motor 2: right unit (Y = 0.6m from center)
param set-default CA_ROTOR2_PX 0.0
param set-default CA_ROTOR2_PY 0.6
param set-default CA_ROTOR2_PZ 0.0

# --- Three control surfaces ---
param set-default CA_SV_CS_COUNT 3

# CS0: Left unit surface (Right Elevon type - reversed for chain-wing)
#   Roll: +0.5 (deflects for positive roll when disturbed left)
#   Pitch: +0.5 (contributes to pitch control)
param set-default CA_SV_CS0_TYPE 6
param set-default CA_SV_CS0_TRQ_R 0.5
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_Y 0.0

# CS1: Center unit surface (Elevator)
#   Pitch only: 1.0
param set-default CA_SV_CS1_TYPE 3
param set-default CA_SV_CS1_TRQ_R 0.0
param set-default CA_SV_CS1_TRQ_P 1.0
param set-default CA_SV_CS1_TRQ_Y 0.0

# CS2: Right unit surface (Left Elevon type - reversed for chain-wing)
#   Roll: -0.5 (deflects for negative roll when disturbed right)
#   Pitch: +0.5 (contributes to pitch control)
param set-default CA_SV_CS2_TYPE 5
param set-default CA_SV_CS2_TRQ_R -0.5
param set-default CA_SV_CS2_TRQ_P 0.5
param set-default CA_SV_CS2_TRQ_Y 0.0

# --- Airspeed parameters from report (cruise 10-15 m/s) ---
param set-default FW_AIRSPD_MIN 8
param set-default FW_AIRSPD_TRIM 12
param set-default FW_AIRSPD_MAX 20
param set-default FW_AIRSPD_STALL 6

# --- Attitude control tuning for chain-wing ---
# Tighter roll response for the semi-flexible structure
param set-default FW_R_TC 0.4
param set-default FW_P_TC 0.4
param set-default FW_R_RMAX 50.0
param set-default FW_P_RMAX_POS 40.0
param set-default FW_P_RMAX_NEG 40.0
param set-default FW_Y_RMAX 30.0

# Yaw heading hold gain for chain-wing stabilization
# Enables active heading tracking via differential thrust + rudder
param set-default FW_YAW_STAB_SC 2.0

# Pitch offset for level flight (report: ~4.5 deg trim angle of attack)
param set-default FW_PSP_OFF 4.5
